/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author dulfu
 */
public class Ingresar extends javax.swing.JFrame {

    /**
     * Creates new form Ingresar
     */
    public Ingresar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        TITULO1 = new javax.swing.JLabel();
        USUARIO = new javax.swing.JLabel();
        CONTRA = new javax.swing.JLabel();
        Ingresar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Contra = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        entra = new javax.swing.JPanel();
        Entrar = new javax.swing.JLabel();
        registrar = new javax.swing.JPanel();
        Registrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Principal"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, -1));

        jPanel3.setBackground(new java.awt.Color(198, 225, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(270, 500));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 230, 180));

        TITULO1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TITULO1.setForeground(new java.awt.Color(0, 0, 0));
        TITULO1.setText("INICIAR SESION");
        jPanel1.add(TITULO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        USUARIO.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        USUARIO.setForeground(new java.awt.Color(0, 0, 0));
        USUARIO.setText("USUARIO");
        jPanel1.add(USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        CONTRA.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CONTRA.setForeground(new java.awt.Color(0, 0, 0));
        CONTRA.setText("CONTRASEÑA");
        jPanel1.add(CONTRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        Ingresar.setBackground(new java.awt.Color(255, 255, 255));
        Ingresar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(153, 153, 153));
        Ingresar.setText("Ingrese usuario");
        Ingresar.setBorder(null);
        Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresarMousePressed(evt);
            }
        });
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 270, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 270, -1));

        Contra.setBackground(new java.awt.Color(255, 255, 255));
        Contra.setForeground(new java.awt.Color(153, 153, 153));
        Contra.setText("**********");
        Contra.setBorder(null);
        Contra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContraMousePressed(evt);
            }
        });
        jPanel1.add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 260, 30));
        Contra.getAccessibleContext().setAccessibleName("");

        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 270, 10));

        entra.setBackground(new java.awt.Color(198, 225, 0));

        Entrar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Entrar.setForeground(new java.awt.Color(0, 0, 0));
        Entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Entrar.setText("ENTRAR");
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout entraLayout = new javax.swing.GroupLayout(entra);
        entra.setLayout(entraLayout);
        entraLayout.setHorizontalGroup(
            entraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        entraLayout.setVerticalGroup(
            entraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(entra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 110, 40));

        registrar.setBackground(new java.awt.Color(198, 225, 0));

        Registrar.setBackground(new java.awt.Color(0, 0, 0));
        Registrar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Registrar.setForeground(new java.awt.Color(0, 0, 0));
        Registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registrar.setText("REGISTRATE");
        Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout registrarLayout = new javax.swing.GroupLayout(registrar);
        registrar.setLayout(registrarLayout);
        registrarLayout.setHorizontalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarLayout.createSequentialGroup()
                .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        registrarLayout.setVerticalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 115, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarActionPerformed

    private void EntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseEntered
      entra.setBackground(new Color (232, 255, 1));
    }//GEN-LAST:event_EntrarMouseEntered

    private void EntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseExited
        entra.setBackground(new Color(198,225,0));
    }//GEN-LAST:event_EntrarMouseExited

    private void RegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseEntered
        registrar.setBackground(new Color(232, 255, 1));
    }//GEN-LAST:event_RegistrarMouseEntered

    private void RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseExited
        registrar.setBackground(new Color (198,225,0));
    }//GEN-LAST:event_RegistrarMouseExited

    private void IngresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMousePressed
       if(Ingresar.getText().equals("Ingrese usuario")){
        Ingresar.setText("");
        Ingresar.setForeground(Color.black);
       }
       if(String.valueOf(Contra.getPassword()).isEmpty()){
        Contra.setText("**********");
        Contra.setForeground(Color.gray);
       }
    }//GEN-LAST:event_IngresarMousePressed

    private void ContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraMousePressed
        if(String.valueOf(Contra.getPassword()).equals("**********")){
        Contra.setText("");
        Contra.setForeground(Color.black);    
        }
        if(Ingresar.getText().isEmpty()){
           Ingresar.setForeground(Color.gray);
           Ingresar.setText("Ingrese usuario");
        }
    }//GEN-LAST:event_ContraMousePressed

    private void RegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMousePressed
        Registro registro = new Registro(null,false);
        registro.setVisible(true);
    }//GEN-LAST:event_RegistrarMousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ingresar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONTRA;
    private javax.swing.JPasswordField Contra;
    private javax.swing.JLabel Entrar;
    private javax.swing.JTextField Ingresar;
    private javax.swing.JLabel Registrar;
    private javax.swing.JLabel TITULO1;
    private javax.swing.JLabel USUARIO;
    private javax.swing.JPanel entra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel registrar;
    // End of variables declaration//GEN-END:variables
}
