/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Entidades.Usuario;
import Modelo.GestioUsuario;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dulfu
 */
public class Registro extends javax.swing.JDialog {

    private GestioUsuario modeloUsuario;

    /**
     * Creates new form Registro
     */
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.modeloUsuario = new GestioUsuario();
    }

    public void limpiarCampos() {
        this.txtnombre.setText("Ingrese Nombre");
        this.Correo.setText("Ingrese Correo");
        this.CC.setText("Ingrese Cedula");
        this.Usuario.setText("Ingrese Usuario");
        this.Contra.setText("**********");
        Contra.setForeground(Color.gray);
        Correo.setForeground(Color.gray);
        txtnombre.setForeground(Color.gray);
        Contra.setForeground(Color.gray);
        Usuario.setForeground(Color.gray);
        CC.setForeground(Color.gray);
    }

    private Usuario leerDatos() throws IOException {
        String tipo = "";
        String nombre = this.txtnombre.getText();
        int cc = Integer.valueOf(this.CC.getText());
        String usuario = this.Usuario.getText();
        String correo = this.Correo.getText();
        String pass = new String(Contra.getPassword());
        if (Particular.isSelected()) {
            tipo = "Particular";
        }

        return new Usuario(cc, nombre, correo, usuario, pass, tipo);
    }

    public void GuardarDatos() {
        try {

            Usuario usuario = this.leerDatos();
            this.modeloUsuario.agregarUsuario(usuario);
            JOptionPane.showMessageDialog(this, "Datos guardados con exito", "COnfirmacion", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex, "Error de archivo", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ie) {
            JOptionPane.showMessageDialog(this, ie, "Error de validacion", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        atras = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        Sapellido = new javax.swing.JSeparator();
        Registrate = new javax.swing.JLabel();
        Lnombre = new javax.swing.JLabel();
        Lusuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Lcorreo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Usuario = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Particular = new javax.swing.JRadioButton();
        regis = new javax.swing.JPanel();
        Regsitrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Contra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        CC = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Principal"); // NOI18N
        setResizable(false);

        atras.setBackground(new java.awt.Color(255, 255, 255));
        atras.setEnabled(false);
        atras.setPreferredSize(new java.awt.Dimension(707, 529));
        atras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura de pantalla 2022-11-27 155034.png"))); // NOI18N
        atras.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 80));

        txtnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(102, 102, 102));
        txtnombre.setText("Ingrese Nombre");
        txtnombre.setBorder(null);
        txtnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnombreMousePressed(evt);
            }
        });
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        atras.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 210, 20));
        atras.add(Sapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 230, -1));

        Registrate.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Registrate.setForeground(new java.awt.Color(51, 51, 51));
        Registrate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registrate.setText("Registrate");
        atras.add(Registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 190, 30));

        Lnombre.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Lnombre.setForeground(new java.awt.Color(0, 0, 0));
        Lnombre.setText("NOMBRE");
        atras.add(Lnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        Lusuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Lusuario.setForeground(new java.awt.Color(0, 0, 0));
        Lusuario.setText("USUARIO");
        atras.add(Lusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));
        atras.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 230, -1));

        Lcorreo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Lcorreo.setForeground(new java.awt.Color(0, 0, 0));
        Lcorreo.setText("CORREO");
        atras.add(Lcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));
        atras.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 230, -1));

        Usuario.setBackground(new java.awt.Color(255, 255, 255));
        Usuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Usuario.setForeground(new java.awt.Color(102, 102, 102));
        Usuario.setText("Ingrese Usuario");
        Usuario.setBorder(null);
        Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuarioMousePressed(evt);
            }
        });
        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioKeyTyped(evt);
            }
        });
        atras.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, -1));

        Correo.setBackground(new java.awt.Color(255, 255, 255));
        Correo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Correo.setForeground(new java.awt.Color(102, 102, 102));
        Correo.setText("Ingrese Correo");
        Correo.setBorder(null);
        Correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CorreoMousePressed(evt);
            }
        });
        Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CorreoKeyTyped(evt);
            }
        });
        atras.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 200, -1));

        Botones.add(Particular);
        Particular.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Particular.setForeground(new java.awt.Color(0, 0, 0));
        Particular.setSelected(true);
        Particular.setText("Particular");
        Particular.setBorder(null);
        atras.add(Particular, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        regis.setBackground(new java.awt.Color(198, 225, 0));

        Regsitrar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Regsitrar.setForeground(new java.awt.Color(0, 0, 0));
        Regsitrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Regsitrar.setText("REGISTRAR");
        Regsitrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regsitrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegsitrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegsitrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegsitrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegsitrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout regisLayout = new javax.swing.GroupLayout(regis);
        regis.setLayout(regisLayout);
        regisLayout.setHorizontalGroup(
            regisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Regsitrar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        regisLayout.setVerticalGroup(
            regisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Regsitrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        atras.add(regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 140, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CONTRASEÑA");
        atras.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));
        atras.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 230, -1));

        Contra.setBackground(new java.awt.Color(255, 255, 255));
        Contra.setForeground(new java.awt.Color(102, 102, 102));
        Contra.setText("**********");
        Contra.setBorder(null);
        Contra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContraMousePressed(evt);
            }
        });
        atras.add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 170, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CEDULA");
        atras.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));
        atras.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 230, -1));

        CC.setBackground(new java.awt.Color(255, 255, 255));
        CC.setBorder(null);
        CC.setForeground(new java.awt.Color(102, 102, 102));
        CC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        CC.setText("Ingrese Cedula");
        CC.setToolTipText("");
        CC.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CCMousePressed(evt);
            }
        });
        CC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CCKeyTyped(evt);
            }
        });
        atras.add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 190, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(atras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(atras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void RegsitrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegsitrarMouseEntered
        regis.setBackground(new Color(232, 255, 1));
    }//GEN-LAST:event_RegsitrarMouseEntered

    private void RegsitrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegsitrarMouseExited
        regis.setBackground(new Color(198, 225, 0));
    }//GEN-LAST:event_RegsitrarMouseExited

    private void RegsitrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegsitrarMousePressed
        if (txtnombre.getText().isEmpty()
                || Correo.getText().isEmpty()
                || Usuario.getText().isEmpty()
                || Contra.getText().isEmpty()
                || CC.getText().isEmpty()
                || txtnombre.getText().equals("")
                || Correo.getText().equals("")
                || Usuario.getText().equals("")
                || Contra.getText().equals("")
                || CC.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Algun campo vacio", "IMPORTANTE", JOptionPane.NO_OPTION);
        } else {
            this.GuardarDatos();
            this.limpiarCampos();
        }
        

    }//GEN-LAST:event_RegsitrarMousePressed

    private void RegsitrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegsitrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegsitrarMouseClicked

    private void txtnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreMousePressed
        if (txtnombre.getText().equals("Ingrese Nombre")) {
            txtnombre.setText("");
            txtnombre.setForeground(Color.black);
        }
        if (String.valueOf(Contra.getPassword()).isEmpty()) {
            Contra.setText("**********");
            Contra.setForeground(Color.gray);
        }
        if (Usuario.getText().isEmpty()) {
            Usuario.setText("Ingrese Usuario");
            Usuario.setForeground(Color.gray);
        }
        if (Correo.getText().isEmpty()) {
            Correo.setText("Ingrese Correo");
            Correo.setForeground(Color.gray);
        }
        if (CC.getText().isEmpty()) {
            CC.setText("Ingrese Cedula");
            CC.setForeground(Color.gray);
        }

    }//GEN-LAST:event_txtnombreMousePressed

    private void CorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorreoMousePressed
        if (Correo.getText().endsWith("Ingrese Correo")) {
            Correo.setText("");
            Correo.setForeground(Color.black);
        }
        if (String.valueOf(Contra.getPassword()).isEmpty()) {
            Contra.setText("**********");
            Contra.setForeground(Color.gray);
        }
        if (Usuario.getText().isEmpty()) {
            Usuario.setText("Ingrese Usuario");
            Usuario.setForeground(Color.gray);
        }
        if (txtnombre.getText().isEmpty()) {
            txtnombre.setText("Ingrese Nombre");
            txtnombre.setForeground(Color.gray);
        }
        if (CC.getText().isEmpty()) {
            CC.setText("Ingrese Cedula");
            CC.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CorreoMousePressed

    private void UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioMousePressed
        if (Usuario.getText().endsWith("Ingrese Usuario")) {
            Usuario.setText("");
            Usuario.setForeground(Color.black);
        }
        if (Correo.getText().isEmpty()) {
            Correo.setText("Ingrese Correo");
            Correo.setForeground(Color.gray);
        }
        if (String.valueOf(Contra.getPassword()).isEmpty()) {
            Contra.setText("**********");
            Contra.setForeground(Color.gray);
        }
        if (txtnombre.getText().isEmpty()) {
            txtnombre.setText("Ingrese Nombre");
            txtnombre.setForeground(Color.gray);
        }
        if (CC.getText().isEmpty()) {
            CC.setText("Ingrese Cedula");
            CC.setForeground(Color.gray);
        }
    }//GEN-LAST:event_UsuarioMousePressed

    private void ContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraMousePressed
        if (String.valueOf(Contra.getPassword()).equals("**********")) {
            Contra.setText("");
            Contra.setForeground(Color.black);
        }
        if (txtnombre.getText().isEmpty()) {
            txtnombre.setText("Ingrese Nombre");
            txtnombre.setForeground(Color.gray);
        }
        if (Correo.getText().isEmpty()) {
            Correo.setText("Ingrese Correo");
            Correo.setForeground(Color.gray);
        }
        if (Usuario.getText().isEmpty()) {
            Usuario.setText("Ingrese Usuario");
            Usuario.setForeground(Color.gray);
        }
        if (CC.getText().isEmpty()) {
            CC.setText("Ingrese Cedula");
            CC.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ContraMousePressed

    private void CCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCMousePressed
        if (CC.getText().endsWith("Ingrese Cedula")) {
            CC.setText("");
            CC.setForeground(Color.black);
        }
        if (Usuario.getText().isEmpty()) {
            Usuario.setText("Ingrese Usuario");
            Usuario.setForeground(Color.gray);
        }
        if (Correo.getText().isEmpty()) {
            Correo.setText("Ingrese Correo");
            Correo.setForeground(Color.gray);
        }
        if (txtnombre.getText().isEmpty()) {
            txtnombre.setText("Ingrese Nombre");
            txtnombre.setForeground(Color.gray);
        }
        if (String.valueOf(Contra.getPassword()).isEmpty()) {
            Contra.setText("**********");
            Contra.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CCMousePressed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char C = evt.getKeyChar();
        if (Character.isDigit(C)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se puede digitar numeros", "IMPORTANTE", JOptionPane.NO_OPTION);
            txtnombre.setCursor(null);
        } else if ((int) evt.getKeyChar() > 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se puede digitar Simbolos", "IMPORTANTE", JOptionPane.NO_OPTION);
            txtnombre.setCursor(null);
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void CCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CCKeyTyped
        char C = evt.getKeyChar();
        if (Character.isLetter(C)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se puede digitar letras", "IMPORTANTE", JOptionPane.NO_OPTION);
            txtnombre.setCursor(null);
        } else if ((int) evt.getKeyChar() > 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se puede digitar Simbolos", "IMPORTANTE", JOptionPane.NO_OPTION);
            CC.setCursor(null);
        }
    }//GEN-LAST:event_CCKeyTyped

    private void UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyTyped
        if ((int) evt.getKeyChar() > 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se puede digitar Simbolos", "IMPORTANTE", JOptionPane.NO_OPTION);
            Usuario.setCursor(null);
        }
    }//GEN-LAST:event_UsuarioKeyTyped

    private void CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreoKeyTyped
        if ((int) evt.getKeyChar() > 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se puede digitar Simbolos", "IMPORTANTE", JOptionPane.NO_OPTION);
            Correo.setCursor(null);
        }
    }//GEN-LAST:event_CorreoKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JFormattedTextField CC;
    private javax.swing.JPasswordField Contra;
    private javax.swing.JTextField Correo;
    private javax.swing.JLabel Lcorreo;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JLabel Lusuario;
    private javax.swing.JRadioButton Particular;
    private javax.swing.JLabel Registrate;
    private javax.swing.JLabel Regsitrar;
    private javax.swing.JSeparator Sapellido;
    private javax.swing.JTextField Usuario;
    private javax.swing.JPanel atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo1;
    private javax.swing.JPanel regis;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

}
